version: 2.1
orbs:
  docker: circleci/docker@1.7.0

jobs:
  build:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout
      - run:
          command: sudo apt-get update && sudo apt-get --no-install-recommends install -y locales-all gettext

      - run:
          name: Install cookiecutter
          command: |
            python3 -m venv venv
            . venv/bin/activate

            pip install cookiecutter

      - run:
          name: Bootstrap the project
          command: |
            . venv/bin/activate
            make test

      - run:
          name: Bootstrap the project with black as formatter
          command: |
            . venv/bin/activate
            make test-with-black

      - persist_to_workspace:
          root: .
          paths:
            - "venv"
            - "testproject"

  coverage:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Codeclimate helper
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            ./cc-test-reporter before-build
            make coverage

      - run:
          name: Upload coverage to codeclimate
          command: |
            cd testproject/django/src && ../../../cc-test-reporter after-build -t coverage.py

workflows:
  version: 2
  ci:
    jobs:
      - build
      - coverage:
          name: Measure test coverage
          requires:
            - build

      - docker/publish:
          name: Make sure docker image is buildable
          requires:
            - build
          image: f213/django
          path: testproject/django
          docker-context: testproject/django
          deploy: false
          attach-at: .
